<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="kyon">

<xacro:arg name="bilevel_codes" default="false" /> <!-- if true, load codes vars from externally provided files-->
<xacro:arg name="sample_idx" default = "0"/>

<xacro:include filename="$(find kyon_urdf)/urdf/utils.urdf.xacro" />

<xacro:include filename="$(find kyon_urdf)/urdf/parts/kinematics_properties.urdf.xacro" />
<!-- NOTE: here we need to include "kinematics_properties" first because "inertial_properties" depends on it-->
<xacro:include filename="$(find kyon_urdf)/urdf/parts/inertial_properties.urdf.xacro" />
<xacro:include filename="$(find kyon_urdf)/urdf/parts/limits.urdf.xacro" />

<link name="base_link"/>

<link name="pelvis">
	<inertial>
		<origin xyz="${Pelvis_x} ${Pelvis_y} ${Pelvis_z}"/>
		<mass value="${Pelvis_mass}"/>
		<inertia ixx="${Pelvis_xx}" ixy="${Pelvis_xy}" ixz="${Pelvis_xz}" iyy="${Pelvis_yy}" iyz="${Pelvis_yz}" izz="${Pelvis_zz}"/>
	</inertial>
	<visual>
		<origin xyz="0.0 0 0.0"  rpy="0.0 0.0 0.0"/>
		<geometry>
	 		<mesh filename="package://kyon_urdf/meshes/mesh_pelvis.stl" scale="0.001 0.001 0.001"/>
		</geometry>
	</visual>
	<collision>
		<origin xyz="0.0 0 0.0"  rpy="0.0 0.0 0.0"/>
		<geometry>
	  		<mesh filename="package://kyon_urdf/meshes/collision/mesh_pelvis.stl" scale="0.001 0.001 0.001"/>
		</geometry>
	</collision>
</link>

<joint name="base_joint" type="fixed">
    <parent link="pelvis"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0" />
</joint>

<link name="imu_link"/>

<joint name="imu_joint" type="fixed">
    <parent link="pelvis"/>
    <child link="imu_link"/>
</joint>

<xacro:if value="${ADD_SENSORS}">
    <xacro:include filename="$(find realsense_gazebo_description)/urdf/_d435i.urdf.xacro" />

    <!-- LEFT D435 CAMERA -->
    <xacro:sensor_d435i parent="pelvis"
        name="D435_left"
        topics_ns="D435_left"
        enable_pointCloud="true"
        align_depth="true"
        unite_imu_method="false"
        visualize="true"
        accel_fps="300"
        gyro_fps="300"
        depth_width="1280"
        depth_height="720"
        depth_fps="10"
        infra_width="1280"
        infra_height="720"
        infra_fps="10"
        color_width="1280"
        color_height="720"
        color_fps="1">

        <origin xyz="0 0.150100 0.109486" rpy="0 0.3490656 1.5707963"/>

    </xacro:sensor_d435i>

    <!-- RIGHT D435 CAMERA -->
    <xacro:sensor_d435i parent="pelvis"
        name="D435_right"
        topics_ns="D435_right"
        enable_pointCloud="true"
        align_depth="true"
        unite_imu_method="false"
        visualize="true"
        accel_fps="300"
        gyro_fps="300"
        depth_width="1280"
        depth_height="720"
        depth_fps="10"
        infra_width="1280"
        infra_height="720"
        infra_fps="10"
        color_width="1280"
        color_height="720"
        color_fps="1">

        <origin xyz="0 -0.150100 0.109486" rpy="0 0.3490656 -1.5707963"/>

    </xacro:sensor_d435i>

    <!-- REAR D435 CAMERA -->
    <!-- <xacro:sensor_d435i parent="pelvis"
        name="D435_rear"
        topics_ns="D435_rear"
        enable_pointCloud="true"
        align_depth="true"
        unite_imu_method="false"
        visualize="true"
        accel_fps="300"
        gyro_fps="300"
        depth_width="1280"
        depth_height="720"
        depth_fps="90"
        infra_width="1280"
        infra_height="720"
        infra_fps="90"
        color_width="1280"
        color_height="720"
        color_fps="30">

        <origin xyz="-0.39 0 0" rpy="0 0.35 3.14"/>

    </xacro:sensor_d435i> -->

    <!-- FRONT1 D435 CAMERA -->
    <xacro:sensor_d435i parent="pelvis"
        name="D435_front1"
        topics_ns="D435_front1"
        enable_pointCloud="true"
        align_depth="true"
        unite_imu_method="false"
        visualize="true"
        accel_fps="300"
        gyro_fps="300"
        depth_width="1280"
        depth_height="720"
        depth_fps="90"
        infra_width="1280"
        infra_height="720"
        infra_fps="90"
        color_width="1280"
        color_height="720"
        color_fps="30">

        <origin xyz="0.526174 0 0.0674608" rpy="0 -0.1745327 0"/>

    </xacro:sensor_d435i>

    <!-- FRONT2 D435 CAMERA -->
    <xacro:sensor_d435i parent="pelvis"
        name="D435_front2"
        topics_ns="D435_front2"
        enable_pointCloud="true"
        align_depth="true"
        unite_imu_method="false"
        visualize="true"
        accel_fps="300"
        gyro_fps="300"
        depth_width="1280"
        depth_height="720"
        depth_fps="90"
        infra_width="1280"
        infra_height="720"
        infra_fps="90"
        color_width="1280"
        color_height="720"
        color_fps="30">

        <origin xyz="0.509601 0 0.00343992" rpy="0 0.9250251 0"/>

    </xacro:sensor_d435i>

    <!-- FRONT3 (down) D435 CAMERA -->
    <!-- <xacro:sensor_d435i parent="pelvis"
        name="D435_front3"
        topics_ns="D435_front3"
        enable_pointCloud="true"
        align_depth="true"
        unite_imu_method="false"
        visualize="true"
        accel_fps="300"
        gyro_fps="300"
        depth_width="1280"
        depth_height="720"
        depth_fps="90"
        infra_width="1280"
        infra_height="720"
        infra_fps="90"
        color_width="1280"
        color_height="720"
        color_fps="30">

        <origin xyz="0.37 0 -0.11" rpy="0 0.75 0"/>

    </xacro:sensor_d435i> -->
    <!-- Velodyne -->
    <!-- <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>
    <xacro:VLP-16 parent="pelvis" name="velodyne" topic="/velodyne_points" hz="10" samples="440">
        <origin xyz="0.36 0 0.11" rpy="0 0 0" />
    </xacro:VLP-16> -->

</xacro:if>

<xacro:if value="${ADD_UPPER_BODY}">
    <xacro:include filename="$(find kyon_urdf)/urdf/parts/arms.urdf.xacro" />
</xacro:if>

<xacro:if value="${ADD_LEGS}">
	<xacro:include filename="$(find kyon_urdf)/urdf/parts/legs.urdf.xacro" />
</xacro:if>

<xacro:if value="${PAYLOAD}">
	<link name="payload_pelvis">
		<inertial>
		    <origin xyz="0.0 0.0 0.0"/>
			<mass value="20"/>
			<inertia ixx="0.13" iyy="0.13" izz="0.13" ixy="0" ixz="0" iyz="0"/>
		</inertial>
		<visual>
			<origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
			<geometry>
				<box size="0.2 0.2 0.2"/>
			</geometry>
			<material name="dark_grey"/>
		</visual>
	</link>
	<joint name="pelvis_to_payload" type="fixed">
		<origin xyz="-0.2 0.0 ${pelvis_height / 2 + 0.1}"/>
		<parent link="pelvis"/>
		<child link="payload_pelvis"/>
	</joint>
</xacro:if>

</robot>
