<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

<!-- include end-effectors -->
<xacro:include filename="$(find kyon_urdf)/urdf/parts/foot_leg.urdf.xacro"/>
<xacro:include filename="$(find kyon_urdf)/urdf/parts/steering_wheel.urdf.xacro"/>
<xacro:include filename="$(find kyon_urdf)/urdf/parts/wheel_leg.urdf.xacro"/>

<!-- macro legs -->
<xacro:macro name="kyon_leg" params="leg_num origin_x origin_y mirror">

<!-- links -->

<link name="hip_roll_${leg_num}_link">
	<inertial>
		<origin xyz="${HipRoll_x} ${HipRoll_y} ${HipRoll_z}"/>
		<mass value="${HipRoll_mass}"/>
		<inertia ixx="${HipRoll_xx}" ixy="${mirror*HipRoll_xy}" ixz="${HipRoll_xz}" iyy="${HipRoll_yy}" iyz="${mirror*HipRoll_yz}" izz="${HipRoll_zz}"/>
	</inertial>
	<visual>
		<origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
	  	<geometry>
	 		<!-- <cylinder radius="${cylinder_radius}" length="${cylinder_length}"/> -->
			<mesh filename="package://kyon_urdf/meshes/mesh_hip-roll.stl" scale="0.001 ${mirror*0.001} 0.001"/>
		</geometry> 
  		<material name="dark_grey"/>
	</visual>
	<collision>
		<origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
		<geometry>
	 		<!-- <cylinder radius="${cylinder_radius}" length="${cylinder_length}"/> -->
			<mesh filename="package://kyon_urdf/meshes/collision/mesh_hip-roll.stl" scale="0.001 ${mirror*0.001} 0.001"/>
		</geometry> 
	</collision>
</link>

<link name="hip_pitch_${leg_num}_link">
	<inertial>
		<origin xyz="${HipPitch_x} ${HipPitch_y} ${HipPitch_z}"/>
		<mass value="${HipPitch_mass}"/>
		<inertia ixx="${HipPitch_xx}" ixy="${HipPitch_xy}" ixz="${HipPitch_xz}" iyy="${HipPitch_yy}" iyz="${HipPitch_yz}" izz="${HipPitch_zz}"/>
	</inertial>
	<visual>
		<origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
	  	<geometry>
	 		<mesh filename="package://kyon_urdf/meshes/mesh_hip-pitch.stl" scale="0.001 0.001 0.001"/>
	  	</geometry>
  		<material name="dark_grey"/>
	</visual>
	<collision>
		<origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
		<geometry>
			<mesh filename="package://kyon_urdf/meshes/collision/mesh_hip-pitch.stl" scale="0.001 0.001 0.001"/>
		</geometry>
	</collision>
</link>

<!-- joints -->

<joint name="hip_roll_${leg_num}" type="revolute">
	<parent link="pelvis"/>
	<child link="hip_roll_${leg_num}_link"/>
	<origin xyz="${origin_x * HipRoll_Ox} ${origin_y * HipRoll_Oy} ${HipRoll_Oz}" rpy="${HipRoll_roll} ${origin_x*HipRoll_pitch} ${HipRoll_yaw}"/>
	<axis xyz="0 0 1"/>
    <limit lower="${hip_roll_lower[leg_num-1]}" upper="${hip_roll_upper[leg_num-1]}" effort="${motorA_effort}" velocity="${motorA_velocity}"/> 
</joint>

<joint name="hip_pitch_${leg_num}" type="revolute">
	<parent link="hip_roll_${leg_num}_link"/>
	<child link="hip_pitch_${leg_num}_link"/>
	<origin xyz="${HipPitch_Ox} ${origin_y * HipPitch_Oy} ${HipPitch_Oz}" rpy="${HipPitch_roll} ${origin_x * origin_y * HipPitch_pitch} ${origin_x * HipPitch_yaw}"/>
	<axis xyz="0 0 1"/>
	<limit lower="${hip_pitch_lower[leg_num-1]}" upper="${hip_pitch_upper[leg_num-1]}" effort="${motorA_effort}" velocity="${motorA_velocity}"/> 
</joint>

<xacro:if value="${ADD_FEET}">
	<xacro:foot_leg leg_num="${leg_num}" parent="hip_pitch_${leg_num}_link" origin_x="${origin_x}" origin_y="${origin_y}" mirror="${mirror}"/>
</xacro:if>

<xacro:if value="${ADD_STEERING_WHEELS}">
	<xacro:steering_wheel leg_num="${leg_num}" parent="hip_pitch_${leg_num}_link" origin_x="${origin_x}" origin_y="${origin_y}" mirror="${mirror}"/>
</xacro:if>

<xacro:if value="${ADD_WHEELS}">
	<xacro:wheel_leg leg_num="${leg_num}" parent="hip_pitch_${leg_num}_link" origin_x="${origin_x}" origin_y="${origin_y}" mirror="${mirror}"/>
</xacro:if>

</xacro:macro>

<!-- /macro legs -->
</robot>
